import { Lilita_One, Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const lilitaOne = Lilita_One({ subsets: ["latin"], weight: ["400"]});
const nunito = Nunito({subsets: ["latin"], weight: ["300", "700", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header lilitaOne={lilitaOne}/> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
